version: 2.1

executors:
  docker:
    docker:
    - image: cimg/base:2020.11
  docker-rust:
    docker:
    - image: cimg/rust:1.48.0

jobs:
  welcome:
    executor: docker
    steps:
    - run: echo "Welcome! Building will start in few seconds" 
  build:
    executor: docker-rust
    resource_class: small
    steps:
    - run: pwd
    - checkout
    - run: rustc ./main.rs
    - run: ls
    - persist_to_workspace:
        root: /home/circleci/project
        paths:
          - main
          - Dockerfile
  test:
    executor: docker
    steps:
    - attach_workspace:
        at: /home/circleci/project
    - run: echo "Running built image"
    - run: ls
    - run: ./main
  publish:
    executor: docker
    steps:
    - attach_workspace:
        at: /home/circleci/project
    - setup_remote_docker:
        docker_layer_caching: false
        version: 19.03.13
    - run: |
          REPO=invermn/rust-hello-world
          TAG=1.0.$CIRCLE_BUILD_NUM
          docker build -t $REPO:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push $REPO:$TAG

workflows:
  regular-build:
    jobs:
    - welcome
    - build
    - test:
        requires:
          - build
    - publish:
        requires:
        - test