version: 2.1

executors:
  docker:
    docker:
    - image: cimg/base
  docker-rust:
    docker:
    - image: cimg/rust

jobs:
  welcome:
    executor: docker
    steps:
    - run: echo "Welcome! Building will start in few seconds" 
  build:
    executor: docker-rust
    resource_class: small
    steps:
    - checkout
    - run: rustc ./main.rs
  run:
    executor: docker
    steps:
    - run: echo "Running built image"
    - run: ./main

workflows:
  regular-build:
    jobs:
    - welcome
    - build
    - run:
        requires:
          - build