version: 2.1

executors:
  docker:
    docker:
    - image: cimg/base:2020.11
  docker-rust:
    docker:
    - image: cimg/rust:1.48.0

jobs:
  welcome:
    executor: docker
    steps:
    - run: echo "Welcome! Building will start in few seconds" 
  build:
    executor: docker-rust
    resource_class: small
    steps:
    - run: pwd
    - checkout
    - run: rustc ./main.rs
    - run: ls
    - persist_to_workspace:
        root: workspace
        paths:
          - main
  run:
    executor: docker
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: echo "Running built image"
    - run: ls
    - run: ./main

workflows:
  regular-build:
    jobs:
    - welcome
    - build
    - run:
        requires:
          - build