version: 2.1

executors:
  docker:
    docker:
    - image: cimg/base
  docker-rust:
    docker:
    - image: cimg/rust

jobs:
  build:
    docker:
    - image: circleci/rust
    steps:
    - checkout
    - run: rustc ./main.rs
    - run: ./main